### PR TITLE
Change onclick to link

### PR DESCRIPTION
**Pull request by stevelacy**
This allows Cmd/Ctrl + Click to open link in new tab instead of replacing the current window

### CODE REVIEW

**Comment by bucaran** [comment]
:+1: Thanks!

**Comment by bucaran** [comment]
@stevelacy Can you update the CSS too? Links are now invisible :sob:

**Comment by stevelacy** [comment]
lol yes willdo

**Comment by stevelacy** [comment]
Ah - just saw your commit

**Comment by bucaran** [comment]
Yeah, no prob :smile:

**Pull request merged**
