### PR TITLE
[features] Looks better on mobile and desktop

### LINKED ISSUE #4: Reduce spacing on small width platforms
https://github.com/fisherman/fisherman.github.io/blob/master/css/style.css#L196

If I am correct, that's the one that makes the spacing between features far apart. I stumbled across this when I am looking if it support mobile platforms.

### PR DESCRIPTION
**Pull request by pickfire**
Fix #4

### CODE REVIEW

**Comment by pickfire** [comment]
It seems like the fish.sh site is not mobile-friendly, maybe you could help them to develop it, I want to help them too but I just start reading about making sites mobile-friendly.

**Comment by jethrokuan** [comment]
We merged your change in the recent push with search plugins. Thanks for pointing this out!

**Comment by pickfire** [comment]
@jethrokuan Thanks a lot. Congrats on becoming a new member and working on the fisherman.sh.

How's it in Singapore? Want to have a visit here in Malaysia?

**Comment by pickfire** [comment]
Well, it still looks a bit ugly after adding the new search plugins feature.

2016-02-23-193003_1600x900_scrot

**Comment by bucaran** [comment]
@pickfire Is this mobile?

**Comment by pickfire** [comment]
@bucaran It is taken from my desktop a raspberry pi 2.

As you can see, the features section at the bottom of the page is badly positioned, I suggest to position it a bit upper.

**Comment by bucaran** [comment]
@pickfire Oh! That's what you mean, yes, I agree.

**Comment by pickfire** [comment]
@bucaran, my website has something similar, it could make the footer dock right at the bottom and I think this is about a similar situation. What I did (If I recall correctly):
```css
html {
  height: 100%;
}

body {
  min-height: calc(100% - 20px);
  position: relative;
}

footer {
  position: absolute;
  bottom: 0; left: 0; right: 0;
}
```

**Comment by bucaran** [comment]
@pickfire The footer is already at the bottom.

**Comment by pickfire** [comment]
@bucaran sorry, I don't mean the footer, I mean the `benefits` section, I have showed the image in another issue. :fireworks:

**Comment by bucaran** [comment]
Yep, I think I did it. Check.

**Comment by pickfire** [comment]
No, it is still:

2016-02-23-210804_1600x900_scrot

**Comment by bucaran** [comment]
it's there you only need to wait a little bit

**Comment by pickfire** [comment]
Okay, no problem. I don't expect to see it done so fast (I might need a few days to get this done). Unless... you are the expert of experts.

**Comment by bucaran** [comment]
Second try. I think it's better now, plus other tweaks. Let me know if you find anything else.

**Comment by pickfire** [comment]
It looks a bit better now, but the description is a bit off. And I hope that the svg icon in the footer can be moved downward a bit to make it looks better.

2016-02-23-212503_1600x900_scrot

**Comment by bucaran** [comment]
What description?

**Comment by bucaran** [comment]
> moved downward a bit to make it looks better.

Can be done.

**Comment by bucaran** [comment]
@pickfire Done.

**Comment by pickfire** [comment]
2016-02-23-213322_1600x900_scrot

**Comment by bucaran** [comment]
Check again.

**Comment by bucaran** [comment]
screencapture-fisherman-sh-1456234889189

**Comment by pickfire** [comment]
Nope, same result, the description for those features section isn't displayed at the first page.

**Comment by bucaran** [comment]
Alright, I'll take another look later.

**Pull request closed without merging**
