### PR TITLE
Open search links in new tab

### PR DESCRIPTION
**Pull request by sijad**

### CODE REVIEW

**Comment by jethrokuan** [comment]
@bucaran I'm good with this. Any thoughts?

**Comment by bucaran** [comment]
This is not this right?

https://github.com/fisherman/fisherman.github.io/pull/7

**Comment by sijad** [comment]
`ctrl/cmd+click` works in all browser but it's a little annoying when I click on plugins title it redirects to Github repo

**Comment by bucaran** [comment]
Hey @sijad thanks. What's the difference with regards to the current behavior? I can't notice the difference.

**Pull request merged**
